SET search_path TO tlp;

DROP INDEX IF EXISTS indx_custinfo_01 CASCADE;
DROP INDEX IF EXISTS indx_custinfo_02 CASCADE;
DROP INDEX IF EXISTS indx_custinfo_03 CASCADE;

DROP INDEX IF EXISTS indx_custsa_01 CASCADE;
DROP INDEX IF EXISTS indx_custsa_02 CASCADE;
DROP INDEX IF EXISTS indx_custsa_03 CASCADE;

DROP INDEX IF EXISTS indx_payment_01 CASCADE;
DROP INDEX IF EXISTS indx_payment_02 CASCADE;
DROP INDEX IF EXISTS indx_payment_03 CASCADE;
DROP INDEX IF EXISTS indx_payment_04 CASCADE;

DROP INDEX IF EXISTS indx_spa_01 CASCADE;
DROP INDEX IF EXISTS indx_spa_02 CASCADE;
DROP INDEX IF EXISTS indx_spa_03 CASCADE;
DROP INDEX IF EXISTS indx_spa_04 CASCADE;

DROP INDEX IF EXISTS indx_custballoon_01 CASCADE;
DROP INDEX IF EXISTS indx_custballoon_02 CASCADE;
DROP INDEX IF EXISTS indx_custballoon_03 CASCADE;
DROP INDEX IF EXISTS indx_custballoon_04 CASCADE;
DROP INDEX IF EXISTS indx_custballoon_05 CASCADE;
DROP INDEX IF EXISTS indx_custballoon_06 CASCADE;