TRUNCATE TABLE ONLY tlp.appcustomer CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.appcustomeraddress CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.historystatus CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.policymaster CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.policybeneficiary CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.policypaid CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.policyrider CONTINUE IDENTITY CASCADE;