SET search_path TO tlpbilling;

DROP INDEX IF EXISTS indx_10 CASCADE;
DROP INDEX IF EXISTS indx_11 CASCADE;
DROP INDEX IF EXISTS indx_12 CASCADE;

DROP INDEX IF EXISTS indx_21 CASCADE;
DROP INDEX IF EXISTS indx_22 CASCADE;
DROP INDEX IF EXISTS indx_23 CASCADE;
DROP INDEX IF EXISTS indx_24 CASCADE;

DROP INDEX IF EXISTS indx_31 CASCADE;
DROP INDEX IF EXISTS indx_32 CASCADE;
DROP INDEX IF EXISTS indx_33 CASCADE;
DROP INDEX IF EXISTS indx_34 CASCADE;

DROP INDEX IF EXISTS indx_41 CASCADE;
DROP INDEX IF EXISTS indx_42 CASCADE;
DROP INDEX IF EXISTS indx_43 CASCADE;