DROP INDEX IF EXISTS indx_cert_01 CASCADE;
DROP INDEX IF EXISTS indx_cert_02 CASCADE;
DROP INDEX IF EXISTS indx_cert_03 CASCADE;
DROP INDEX IF EXISTS indx_cert_04 CASCADE;

DROP INDEX IF EXISTS indx_certlinker_01 CASCADE;
DROP INDEX IF EXISTS indx_certlinker_02 CASCADE;
DROP INDEX IF EXISTS indx_certlinker_03 CASCADE;

DROP INDEX IF EXISTS indx_certmapping_01 CASCADE;
DROP INDEX IF EXISTS indx_certmapping_02 CASCADE;
DROP INDEX IF EXISTS indx_certmapping_03 CASCADE;

DROP INDEX IF EXISTS indx_certrider_01 CASCADE;
DROP INDEX IF EXISTS indx_certrider_02 CASCADE;
DROP INDEX IF EXISTS indx_certrider_03 CASCADE;

DROP INDEX IF EXISTS indx_compensateid_01 CASCADE;
DROP INDEX IF EXISTS indx_compensateid_02 CASCADE;
DROP INDEX IF EXISTS indx_compensateid_03 CASCADE;

DROP INDEX IF EXISTS indx_customer_01 CASCADE;
DROP INDEX IF EXISTS indx_customer_02 CASCADE;
DROP INDEX IF EXISTS indx_customer_03 CASCADE;
DROP INDEX IF EXISTS indx_customer_04 CASCADE;

DROP INDEX IF EXISTS indx_detcert_01 CASCADE;
DROP INDEX IF EXISTS indx_detcert_02 CASCADE;
DROP INDEX IF EXISTS indx_detcert_03 CASCADE;

DROP INDEX IF EXISTS indx_name_01 CASCADE;
DROP INDEX IF EXISTS indx_name_02 CASCADE;
DROP INDEX IF EXISTS indx_name_03 CASCADE;

DROP INDEX IF EXISTS indx_person_01 CASCADE;
DROP INDEX IF EXISTS indx_person_02 CASCADE;
DROP INDEX IF EXISTS indx_person_03 CASCADE;
DROP INDEX IF EXISTS indx_person_04 CASCADE;
DROP INDEX IF EXISTS indx_person_05 CASCADE;
DROP INDEX IF EXISTS indx_person_06 CASCADE;
DROP INDEX IF EXISTS indx_person_07 CASCADE;
DROP INDEX IF EXISTS indx_person_08 CASCADE;

DROP INDEX IF EXISTS indx_policy_01 CASCADE;