SET search_path TO tlp;

DROP INDEX IF EXISTS indx_appcust_01 CASCADE;
DROP INDEX IF EXISTS indx_appcust_02 CASCADE;
DROP INDEX IF EXISTS indx_appcust_03 CASCADE;
DROP INDEX IF EXISTS indx_appcust_04 CASCADE;

DROP INDEX IF EXISTS indx_appcustadd_01 CASCADE;

DROP INDEX IF EXISTS indx_policymas_01 CASCADE;
DROP INDEX IF EXISTS indx_policymas_02 CASCADE;
DROP INDEX IF EXISTS indx_policymas_03 CASCADE;
DROP INDEX IF EXISTS indx_policymas_04 CASCADE;

DROP INDEX IF EXISTS indx_prodset_01 CASCADE;

DROP INDEX IF EXISTS indx_historysta_01 CASCADE;
DROP INDEX IF EXISTS indx_historysta_02 CASCADE;
DROP INDEX IF EXISTS indx_historysta_03 CASCADE;

DROP INDEX IF EXISTS indx_policybene_01 CASCADE;

DROP INDEX IF EXISTS indx_policyrid_01 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_02 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_03 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_04 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_05 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_06 CASCADE;

DROP INDEX IF EXISTS indx_statusmas_01 CASCADE;

DROP INDEX IF EXISTS indx_policypaid_01 CASCADE;
DROP INDEX IF EXISTS indx_policypaid_02 CASCADE;
DROP INDEX IF EXISTS indx_policypaid_03 CASCADE;

DROP INDEX IF EXISTS indx_prodridset_01 CASCADE;

DROP INDEX IF EXISTS  indx_custinfo_01 CASCADE;
DROP INDEX IF EXISTS  indx_custinfo_02 CASCADE;
DROP INDEX IF EXISTS  indx_custinfo_03 CASCADE;

DROP INDEX IF EXISTS  indx_custsa_01 CASCADE;
DROP INDEX IF EXISTS  indx_custsa_02 CASCADE;
DROP INDEX IF EXISTS  indx_custsa_03 CASCADE;

DROP INDEX IF EXISTS  indx_payment_01 CASCADE;
DROP INDEX IF EXISTS  indx_payment_02 CASCADE;
DROP INDEX IF EXISTS  indx_payment_03 CASCADE;
DROP INDEX IF EXISTS  indx_payment_04 CASCADE;

DROP INDEX IF EXISTS  indx_spa_01 CASCADE;
DROP INDEX IF EXISTS  indx_spa_02 CASCADE;
DROP INDEX IF EXISTS  indx_spa_03 CASCADE;
DROP INDEX IF EXISTS  indx_spa_04 CASCADE;


DROP INDEX IF EXISTS  indx_custballoon_01 CASCADE;
DROP INDEX IF EXISTS  indx_custballoon_02 CASCADE;
DROP INDEX IF EXISTS  indx_custballoon_03 CASCADE;
DROP INDEX IF EXISTS  indx_custballoon_04 CASCADE;
DROP INDEX IF EXISTS  indx_custballoon_05 CASCADE;
DROP INDEX IF EXISTS  indx_custballoon_06 CASCADE;