SET search_path TO dm;

DROP INDEX IF EXISTS indx_cert_01 CASCADE;
DROP INDEX IF EXISTS indx_cert_02 CASCADE;
DROP INDEX IF EXISTS indx_cert_03 CASCADE;
DROP INDEX IF EXISTS indx_cert_04 CASCADE;

DROP INDEX IF EXISTS indx_certlinker_01 CASCADE;
DROP INDEX IF EXISTS indx_certlinker_02 CASCADE;
DROP INDEX IF EXISTS indx_certlinker_03 CASCADE;

DROP INDEX IF EXISTS indx_certmapping_01 CASCADE;
DROP INDEX IF EXISTS indx_certmapping_02 CASCADE;
DROP INDEX IF EXISTS indx_certmapping_03 CASCADE;

DROP INDEX IF EXISTS indx_certrider_01 CASCADE;
DROP INDEX IF EXISTS indx_certrider_02 CASCADE;
DROP INDEX IF EXISTS indx_certrider_03 CASCADE;

DROP INDEX IF EXISTS indx_compensateid_01 CASCADE;
DROP INDEX IF EXISTS indx_compensateid_02 CASCADE;
DROP INDEX IF EXISTS indx_compensateid_03 CASCADE;

DROP INDEX IF EXISTS indx_customer_01 CASCADE;
DROP INDEX IF EXISTS indx_customer_02 CASCADE;
DROP INDEX IF EXISTS indx_customer_03 CASCADE;
DROP INDEX IF EXISTS indx_customer_04 CASCADE;

DROP INDEX IF EXISTS indx_detcert_01 CASCADE;
DROP INDEX IF EXISTS indx_detcert_02 CASCADE;
DROP INDEX IF EXISTS indx_detcert_03 CASCADE;

DROP INDEX IF EXISTS indx_name_01 CASCADE;
DROP INDEX IF EXISTS indx_name_02 CASCADE;
DROP INDEX IF EXISTS indx_name_03 CASCADE;

DROP INDEX IF EXISTS indx_person_01 CASCADE;
DROP INDEX IF EXISTS indx_person_02 CASCADE;
DROP INDEX IF EXISTS indx_person_03 CASCADE;
DROP INDEX IF EXISTS indx_person_04 CASCADE;
DROP INDEX IF EXISTS indx_person_05 CASCADE;
DROP INDEX IF EXISTS indx_person_06 CASCADE;
DROP INDEX IF EXISTS indx_person_07 CASCADE;
DROP INDEX IF EXISTS indx_person_08 CASCADE;

DROP INDEX IF EXISTS indx_policy_01 CASCADE;

DROP INDEX IF EXISTS indx_premrate_01 CASCADE;

DROP INDEX IF EXISTS indx_tpdrate_01 CASCADE;

DROP INDEX IF EXISTS indx_beneficiary_01 CASCADE;
DROP INDEX IF EXISTS indx_beneficiary_02 CASCADE;
DROP INDEX IF EXISTS indx_beneficiary_03 CASCADE;
DROP INDEX IF EXISTS indx_beneficiary_04 CASCADE;

DROP INDEX IF EXISTS indx_address_01 CASCADE;


DROP INDEX IF EXISTS indx_ordmast_01 CASCADE;
DROP INDEX IF EXISTS indx_ordmast_02 CASCADE;
DROP INDEX IF EXISTS indx_ordmast_03 CASCADE;

DROP INDEX IF EXISTS indx_rider_01 CASCADE;
DROP INDEX IF EXISTS indx_rider_02 CASCADE;
DROP INDEX IF EXISTS indx_rider_03 CASCADE;

DROP INDEX IF EXISTS indx_orctrl_01 CASCADE;
DROP INDEX IF EXISTS indx_orctrl_02 CASCADE;
DROP INDEX IF EXISTS indx_orctrl_03 CASCADE;

DROP INDEX IF EXISTS indx_rprider_01 CASCADE;
DROP INDEX IF EXISTS indx_rprider_02 CASCADE;
DROP INDEX IF EXISTS indx_rprider_03 CASCADE;

DROP INDEX IF EXISTS indx_extrapremium_01 CASCADE;
DROP INDEX IF EXISTS indx_extrapremium_02 CASCADE;
DROP INDEX IF EXISTS indx_extrapremium_03 CASCADE;
DROP INDEX IF EXISTS indx_extrapremium_04 CASCADE;

DROP INDEX IF EXISTS indx_remark_01 CASCADE;
DROP INDEX IF EXISTS indx_remark_02 CASCADE;
DROP INDEX IF EXISTS indx_remark_03 CASCADE;
DROP INDEX IF EXISTS indx_remark_04 CASCADE;

DROP INDEX IF EXISTS indx_claim_01 CASCADE;
DROP INDEX IF EXISTS indx_claim_02 CASCADE;
DROP INDEX IF EXISTS indx_claim_03 CASCADE;
DROP INDEX IF EXISTS indx_claim_04 CASCADE;

DROP INDEX IF EXISTS indx_eclm_01 CASCADE;
DROP INDEX IF EXISTS indx_eclm_02 CASCADE;
DROP INDEX IF EXISTS indx_eclm_03 CASCADE;
DROP INDEX IF EXISTS indx_eclm_04 CASCADE;

DROP INDEX IF EXISTS indx_dthordo_01 CASCADE;
DROP INDEX IF EXISTS indx_dthordo_02 CASCADE;
DROP INDEX IF EXISTS indx_dthordo_03 CASCADE;
DROP INDEX IF EXISTS indx_dthordo_04 CASCADE;
DROP INDEX IF EXISTS indx_dthordo_05 CASCADE;
DROP INDEX IF EXISTS indx_dthordo_06 CASCADE;

DROP INDEX IF EXISTS indx_ridordo_01 CASCADE;
DROP INDEX IF EXISTS indx_ridordo_02 CASCADE;
DROP INDEX IF EXISTS indx_ridordo_03 CASCADE;
DROP INDEX IF EXISTS indx_ridordo_04 CASCADE;

DROP INDEX IF EXISTS indx_dhsordo_01 CASCADE;
DROP INDEX IF EXISTS indx_dhsordo_02 CASCADE;
DROP INDEX IF EXISTS indx_dhsordo_03 CASCADE;
DROP INDEX IF EXISTS indx_dhsordo_04 CASCADE;

DROP INDEX IF EXISTS indx_bnfordo_01 CASCADE;
DROP INDEX IF EXISTS indx_bnfordo_02 CASCADE;
DROP INDEX IF EXISTS indx_bnfordo_03 CASCADE;
DROP INDEX IF EXISTS indx_bnfordo_04 CASCADE;

DROP INDEX IF EXISTS indx_oacm_01 CASCADE;
DROP INDEX IF EXISTS indx_oacm_02 CASCADE;
DROP INDEX IF EXISTS indx_oacm_03 CASCADE;
DROP INDEX IF EXISTS indx_oacm_04 CASCADE;
DROP INDEX IF EXISTS indx_oacm_05 CASCADE;
DROP INDEX IF EXISTS indx_oacm_06 CASCADE;

DROP INDEX IF EXISTS indx_hordods_01 CASCADE;
DROP INDEX IF EXISTS indx_hordods_02 CASCADE;
DROP INDEX IF EXISTS indx_hordods_03 CASCADE;
DROP INDEX IF EXISTS indx_hordods_04 CASCADE;
DROP INDEX IF EXISTS indx_hordods_05 CASCADE;

DROP INDEX IF EXISTS indx_pay_01 CASCADE;
DROP INDEX IF EXISTS indx_pay_02 CASCADE;
DROP INDEX IF EXISTS indx_pay_03 CASCADE;
DROP INDEX IF EXISTS indx_pay_04 CASCADE;

DROP INDEX IF EXISTS indx_insmemo_01 CASCADE;
DROP INDEX IF EXISTS indx_insmemo_02 CASCADE;
DROP INDEX IF EXISTS indx_insmemo_03 CASCADE;
DROP INDEX IF EXISTS indx_insmemo_04 CASCADE;
DROP INDEX IF EXISTS indx_insmemo_05 CASCADE;
DROP INDEX IF EXISTS indx_insmemo_06 CASCADE;

DROP INDEX IF EXISTS indx_voiordo_01 CASCADE;
DROP INDEX IF EXISTS indx_voiordo_02 CASCADE;
DROP INDEX IF EXISTS indx_voiordo_03 CASCADE;
DROP INDEX IF EXISTS indx_voiordo_04 CASCADE;
DROP INDEX IF EXISTS indx_voiordo_05 CASCADE;

DROP INDEX IF EXISTS indx_cmem_01 CASCADE;
DROP INDEX IF EXISTS indx_cmem_02 CASCADE;
DROP INDEX IF EXISTS indx_cmem_03 CASCADE; 
DROP INDEX IF EXISTS indx_cmem_04 CASCADE;

DROP INDEX IF EXISTS indx_odis_01 CASCADE;
DROP INDEX IF EXISTS indx_odis_02 CASCADE;
DROP INDEX IF EXISTS indx_odis_03 CASCADE;
DROP INDEX IF EXISTS indx_odis_04 CASCADE;

DROP INDEX IF EXISTS indx_ords_01 CASCADE;
DROP INDEX IF EXISTS indx_ords_02 CASCADE;
DROP INDEX IF EXISTS indx_ords_03 CASCADE;
DROP INDEX IF EXISTS indx_ords_04 CASCADE;
DROP INDEX IF EXISTS indx_ords_05 CASCADE;



