SET search_path TO tlp;

DROP INDEX IF EXISTS indx_appcust_01 CASCADE;
DROP INDEX IF EXISTS indx_appcust_02 CASCADE;
DROP INDEX IF EXISTS indx_appcust_03 CASCADE;
DROP INDEX IF EXISTS indx_appcust_04 CASCADE;

DROP INDEX IF EXISTS indx_appcustadd_01 CASCADE;
DROP INDEX IF EXISTS indx_appcustadd_02 CASCADE;
DROP INDEX IF EXISTS indx_appcustadd_03 CASCADE;

DROP INDEX IF EXISTS indx_policymas_01 CASCADE;
DROP INDEX IF EXISTS indx_policymas_02 CASCADE;
DROP INDEX IF EXISTS indx_policymas_03 CASCADE;
DROP INDEX IF EXISTS indx_policymas_04 CASCADE;

DROP INDEX IF EXISTS indx_historysta_01 CASCADE;
DROP INDEX IF EXISTS indx_historysta_02 CASCADE;
DROP INDEX IF EXISTS indx_historysta_03 CASCADE;

DROP INDEX IF EXISTS indx_policybene_01 CASCADE;
DROP INDEX IF EXISTS indx_policybene_02 CASCADE;
DROP INDEX IF EXISTS indx_policybene_03 CASCADE;

DROP INDEX IF EXISTS indx_policyrid_01 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_02 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_03 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_04 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_05 CASCADE;
DROP INDEX IF EXISTS indx_policyrid_06 CASCADE;

DROP INDEX IF EXISTS indx_policypaid_01 CASCADE;
DROP INDEX IF EXISTS indx_policypaid_02 CASCADE;
DROP INDEX IF EXISTS indx_policypaid_03 CASCADE;
DROP INDEX IF EXISTS indx_policypaid_04 CASCADE;
DROP INDEX IF EXISTS indx_policypaid_05 CASCADE;