select count(0) from tlp.appcustomer;
select count(0) from tlp.appcustomeraddress;
select count(0) from tlp.historystatus;
select count(0) from tlp.policybeneficiary;
select count(0) from tlp.policymaster;
select count(0) from tlp.policypaid;
select count(0) from tlp.policyrider;
select count(0) AS masproduct from tlp.masproduct;
select count(0) AS masproductcoverage from tlp.masproductcoverage;
select count(0) AS masproductcoverageclaim from tlp.masproductcoverageclaim;
select count(0) AS claimpayment from tlp.claimpayment;
select count(0) AS claimpaymentdetail from tlp.claimpaymentdetail;
select count(0) AS claimregisterdetail from tlp.claimregisterdetail;
select count(0) AS claimregisterheader from tlp.claimregisterheader;