SET search_path TO dm;

DROP INDEX IF EXISTS indx_compensateid_01 CASCADE;
DROP INDEX IF EXISTS indx_compensateid_02 CASCADE;
DROP INDEX IF EXISTS indx_compensateid_03 CASCADE; 

DROP INDEX IF EXISTS indx_customer_01 CASCADE; 
DROP INDEX IF EXISTS indx_customer_02 CASCADE; 
DROP INDEX IF EXISTS indx_customer_03 CASCADE; 
DROP INDEX IF EXISTS indx_customer_04 CASCADE; 

DROP INDEX IF EXISTS indx_name_01 CASCADE; 
DROP INDEX IF EXISTS indx_name_02 CASCADE; 
DROP INDEX IF EXISTS indx_name_03 CASCADE; 

DROP INDEX IF EXISTS indx_person_01 CASCADE; 
DROP INDEX IF EXISTS indx_person_02 CASCADE; 
DROP INDEX IF EXISTS indx_person_03 CASCADE; 
DROP INDEX IF EXISTS indx_person_04 CASCADE;
DROP INDEX IF EXISTS indx_person_05 CASCADE;
DROP INDEX IF EXISTS indx_person_06 CASCADE;
DROP INDEX IF EXISTS indx_person_07 CASCADE;
DROP INDEX IF EXISTS indx_person_08 CASCADE;

DROP INDEX IF EXISTS indx_policy_01 CASCADE;

DROP INDEX IF EXISTS indx_cert_01 CASCADE; 
DROP INDEX IF EXISTS indx_cert_02 CASCADE;
DROP INDEX IF EXISTS indx_cert_03 CASCADE;
DROP INDEX IF EXISTS indx_cert_04 CASCADE;

DROP INDEX IF EXISTS indx_detcert_01 CASCADE;
DROP INDEX IF EXISTS indx_detcert_02 CASCADE;
DROP INDEX IF EXISTS indx_detcert_03 CASCADE;

DROP INDEX IF EXISTS indx_certrider_01 CASCADE;
DROP INDEX IF EXISTS indx_certrider_02 CASCADE;
DROP INDEX IF EXISTS indx_certrider_03 CASCADE;

DROP INDEX IF EXISTS indx_clrctrl_01 CASCADE; 
DROP INDEX IF EXISTS indx_clrctrl_02 CASCADE;
DROP INDEX IF EXISTS indx_clrctrl_03 CASCADE;
DROP INDEX IF EXISTS indx_clrctrl_04 CASCADE; 
DROP INDEX IF EXISTS indx_clrctrl_05 CASCADE; 

DROP INDEX IF EXISTS indx_certmapping_01 CASCADE;
DROP INDEX IF EXISTS indx_certmapping_02 CASCADE;
DROP INDEX IF EXISTS indx_certmapping_03 CASCADE;

DROP INDEX IF EXISTS indx_mgclaim_01 CASCADE;
DROP INDEX IF EXISTS indx_mgclaim_02 CASCADE; 
DROP INDEX IF EXISTS indx_mgclaim_03 CASCADE; 
DROP INDEX IF EXISTS indx_mgclaim_04 CASCADE; 
DROP INDEX IF EXISTS indx_mgclaim_05 CASCADE; 

DROP INDEX IF EXISTS indx_mgorder_01 CASCADE; 
DROP INDEX IF EXISTS indx_mgorder_02 CASCADE; 
DROP INDEX IF EXISTS indx_mgorder_03 CASCADE; 

DROP INDEX IF EXISTS indx_mgcfpolicy_01 CASCADE;
DROP INDEX IF EXISTS indx_mgcfpolicy_02 CASCADE;
DROP INDEX IF EXISTS indx_mgcfpolicy_03 CASCADE; 
DROP INDEX IF EXISTS indx_mgcfpolicy_04 CASCADE; 

DROP INDEX IF EXISTS indx_mgcfpay_01 CASCADE; 
DROP INDEX IF EXISTS indx_mgcfpay_02 CASCADE; 
DROP INDEX IF EXISTS indx_mgcfpay_03 CASCADE; 
DROP INDEX IF EXISTS indx_mgcfpay_04 CASCADE; 
DROP INDEX IF EXISTS indx_mgcfpay_05 CASCADE; 
DROP INDEX IF EXISTS indx_mgcfpay_06 CASCADE; 
DROP INDEX IF EXISTS indx_mgcfpay_07 CASCADE; 

DROP INDEX IF EXISTS indx_mghis_01 CASCADE; 
DROP INDEX IF EXISTS indx_mghis_02 CASCADE; 
DROP INDEX IF EXISTS indx_mghis_03 CASCADE; 
DROP INDEX IF EXISTS indx_mghis_04 CASCADE; 
DROP INDEX IF EXISTS indx_mghis_05 CASCADE; 
DROP INDEX IF EXISTS indx_mghis_06 CASCADE; 

DROP INDEX IF EXISTS indx_mginsmemo_01 CASCADE; 
DROP INDEX IF EXISTS indx_mginsmemo_02 CASCADE; 
DROP INDEX IF EXISTS indx_mginsmemo_03 CASCADE; 
DROP INDEX IF EXISTS indx_mginsmemo_04 CASCADE; 
DROP INDEX IF EXISTS indx_mginsmemo_05 CASCADE; 

DROP INDEX IF EXISTS indx_mginterest_01 CASCADE; 
DROP INDEX IF EXISTS indx_mginterest_02 CASCADE; 
DROP INDEX IF EXISTS indx_mginterest_03 CASCADE; 
DROP INDEX IF EXISTS indx_mginterest_04 CASCADE; 
DROP INDEX IF EXISTS indx_mginterest_05 CASCADE; 
DROP INDEX IF EXISTS indx_mginterest_06 CASCADE; 

DROP INDEX IF EXISTS indx_mgreceiver_01 CASCADE;
DROP INDEX IF EXISTS indx_mgreceiver_02 CASCADE; 
DROP INDEX IF EXISTS indx_mgreceiver_03 CASCADE; 
DROP INDEX IF EXISTS indx_mgreceiver_04 CASCADE; 
DROP INDEX IF EXISTS indx_mgreceiver_05 CASCADE; 

DROP INDEX IF EXISTS indx_queue_01 CASCADE; 
DROP INDEX IF EXISTS indx_queue_01 CASCADE; 
DROP INDEX IF EXISTS indx_queue_01 CASCADE; 
DROP INDEX IF EXISTS indx_queue_01 CASCADE; 
DROP INDEX IF EXISTS indx_queue_01 CASCADE; 
