TRUNCATE TABLE ONLY tlp.splitpremiumamout CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.customersa CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.customerinfo CONTINUE IDENTITY CASCADE;
TRUNCATE TABLE ONLY tlp.payment CONTINUE IDENTITY CASCADE;